language: node_js
node_js:
  - "4.1"

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - psql -c 'create database todo;' -U postgres
  - npm install -g gulp
  - "export NODE_ENV=ci"
  - gulp db:migrate
  - gulp db:seed
  - gulp &

script: npm run test:unit
